Update build_openstack_packages to support downstream gitlab
This pr:
* Since downstream gerrit repos is moved to gitlab. Zuul works
  with gitlab and it clones the gitlab repos in job workspace.
  Use the zuul clonned content instead of clonning from gerrit or
  gitlab. As zuul already checks out the source code. Let's reuse it
  for dlrn purpose by updating packages.yml.

* Drop branch creation task as it is no longer needed.

* For RHOS-18, downstream distgit uses rhoso-18 not rhos. It also
  updates the project.ini to reflect the same.

Note: While running build_openstack_packages in containers using
make run_ctx_molecule, we are hitting following error in rpmbuild.log in
CI and in local environment.
```
DEBUG: unshare(67239936) failed, falling back to unshare(131072)
ERROR: Namespace unshare failed.
```
Based on this bug
https://bugzilla.redhat.com/show_bug.cgi?id=1336750#c3,
By passing `--cap-add=SYS_ADMIN` fixes the issue.

Signed-off-by: Chandan Kumar (raukadah) <raukadah@gmail.com>

Related-Jira: https://issues.redhat.com/browse/OSPRH-13660