Add openstack documentation fragments
[1] was merged with a reference to the openstack documentation fragment,
this needs to be in our repo for the documentation job to succeed and
build.

Error: https://github.com/openstack-k8s-operators/ci-framework/actions/runs/8537234033/job/23387381595?pr=1345#step:4:204
Docs: https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#documentation-fragments

[1] https://github.com/openstack-k8s-operators/ci-framework/pull/1296