[uni01alpha] Add support for testing DT
This change adds networker nodes to solve the below error
observed during gate checking.

error: accumulating components: accumulateDirectory: "recursed accumulation of path
'/home/zuul/src/github.com/openstack-k8s-operators/architecture/dt/uni01alpha/networker':
accumulating components: accumulateDirectory: \"recursed accumulation of path
'/home/zuul/src/github.com/openstack-k8s-operators/architecture/lib/dataplane':
accumulating components: accumulateDirectory: \\\"recursed accumulation of path
'/home/zuul/src/github.com/openstack-k8s-operators/architecture/lib/dataplane/nodeset':
fieldPath `data.nodeset.nodes` is missing for replacement source
ConfigMap.[noVer].[noGrp]/edpm-nodeset-values.[noNs]\\\"\""

Signed-off-by: Pragadeeswaran Sathyanarayanan <psathyan@redhat.com>