Set the revision of ansible-podman-collections to 'main'
Installing ci-framework requirements fails on:
ansible-galaxy collection install --upgrade --force --timeout=120 /home/zuul/src/github.com/openstack-k8s-operators/ci-framework
Cloning into '/home/zuul/.ansible/tmp/ansible-local-24798o634gjev/tmpjj8gurw9/ansible-podman-collectionsacd5cco5'...
error: pathspec 'master' did not match any file(s) known to git
ERROR! Failed to switch a cloned Git repo `https://github
.com/containers/ansible-podman-collections` to the requested revision
 `master`.

 It seems that the branch of ansible-podman-collections was renamed
 from 'master' to 'main'.