Skip watcher containers for downstream
Watcher related packages got added in RDO antelope but not available in
OSP-18 downstream.

https://github.com/openstack-k8s-operators/tcib/pull/215 adds watcher
container in tcib. Since downstream tcib jobs install the tcib rpm from
main branch so it may break downstream container build and component
job.

So in order to avoid breakage, we are skip building watcher related
containers.

Note: It also fixes the exclude conditional to check existence of
release key in exclude var to avoid following error:
```
''dict object'' has no attribute ''master'''
```

Depends-On: https://github.com/openstack-k8s-operators/tcib/pull/215

Signed-off-by: Chandan Kumar <raukadah@gmail.com>