Add a workaround to fix podman mkdir /run/user/1000: permission denied
On RHEL-9.4 with podman podman-4.9.4-0.1.el9.x86_64, we are facing
following issue while pulling images using podman.
```
[zuul@titan102 ~]$ podman images
WARN[0000] RunRoot is pointing to a path (/run/user/1000/containers) which is not writable. Most likely podman will fail.
Error: creating events dirs: mkdir /run/user/1000: permission denied
```

Based on https://github.com/containers/podman/issues/5049#issuecomment-1348628646
running `loginctl enable-linger $USER` fixes the issue.

Signed-off-by: Chandan Kumar <raukadah@gmail.com>