[set_openstack_containers] Clond openstack-operator for molecule
After merging change [1] molecule job is failing because of missing
resouces:

    + oc apply -k /home/zuul/src/github.com/openstack-k8s-operators/install_yamls/out/operator/openstack-operator/config/crd --server-side
    error: must build at directory: not a valid directory: evalsymlink failure on '/home/zuul/src/github.com/openstack-k8s-operators/install_yamls/out/operator/openstack-operator/config/crd' : lstat /home/zuul/src/github.com/openstack-k8s-operators/install_yamls/out/operator: no such file or directory
    make: *** [Makefile:1048: openstack_crds] Error 1

[1] https://github.com/openstack-k8s-operators/install_yamls/commit/39fd4b5be79bbb3936e1d46ed329cd283baf8db9

Signed-off-by: Daniel Pawlik <dpawlik@redhat.com>