[cert_manager] Add retry when installing cert_manager
In some cases, the CI if failing on various issues not related to the
cert manager, but more related to OpenShift cluster that can be
unstable.
Example error:

    TASK [cert_manager : Create the cifmw_cert_manager_operator_namespace namespace
    (...)
    File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 576, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))
  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.crc.testing', port=6443): Max retries exceeded with url: /api/v1/namespaces/cert-manager-operator (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f551ceaba00>: Failed to establish a new connection: [Errno 111] Connection refused'))
  (...)

Retry with delay should avoid potential issues when installing cert
manager.

Signed-off-by: Daniel Pawlik <dpawlik@redhat.com>