[devscripts] Disable remember_owner
In some CI, there is an error:

    error: Failed to start domain 'somevm'
    error: Requested operation is not valid:
    Setting different SELinux label on /home/zuul/ci-framework-data/some.qcow2 which is already in use

where later there is an error:

    TASK [libvirt_manager : Start vm name=cifmw-{{ vm }}, state=running, uri=qemu:///system] ***
    ...
    task path: /home/zuul/src/github.com/openstack-k8s-operators/ci-framework/roles/libvirt_manager/tasks/start_one_vm.yml:2
    fatal: [localhost -> hypervisor(somehost)]: FAILED! =>
        attempts: 5
        changed: false
        msg: 'Cannot open log file: ''/var/log/libvirt/qemu/somevm.log'':
          Device or resource busy'

Disable the the feature as it is not needed in the CI.

Signed-off-by: Daniel Pawlik <dpawlik@redhat.com>