Add retries to openshift_obs deployment and pod
We observe the following errors randomly occurring from
`kubernetes.core.k8s_info` module:
`AttributeError: ''NoneType'' object has no attribute ''status''`.

This may be because the OpenShift cluster gets overwhelmed
and sometimes the module receives the unexpected response,
so in `custom_condition()` in `plugins/module_utils/k8s/waiter.py`
there is no `status` field in `resource` [1].

As a mitigation, let's try retrying the task after some delay.

[1] https://github.com/ansible-collections/kubernetes.core/blob/main/plugins/module_utils/k8s/waiter.py#L86